version: '3.8'

# Development overrides
services:
  gameplan-app:
    environment:
      - NODE_ENV=development
      - AUTO_LOGIN_ADMIN=true
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  mongo-express:
    profiles: []  # Enable mongo-express by default in development
