services:
  gameplan-app:
    build: .
    container_name: gameplan-app
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - MONGO_URI=mongodb://gameplan_user:${MONGO_PASSWORD}@mongodb:27017/gameplan?authSource=gameplan
      - SESSION_SECRET=${SESSION_SECRET}
      - RAWG_API_KEY=${RAWG_API_KEY}
      - AUTO_LOGIN_ADMIN=${AUTO_LOGIN_ADMIN:-false}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - gameplan-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  mongodb:
    image: mongo:7.0
    container_name: gameplan-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=gameplan
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - gameplan-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo-express:
    image: mongo-express:1.0.2
    container_name: gameplan-mongo-express
    restart: unless-stopped
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://admin:${MONGO_ROOT_PASSWORD}@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USER:-admin}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - gameplan-network
    profiles:
      - tools

  init-admin:
    build: .
    container_name: gameplan-init-admin
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MONGO_URI=mongodb://gameplan_user:${MONGO_PASSWORD}@mongodb:27017/gameplan?authSource=gameplan
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_NAME=${ADMIN_NAME:-GamePlan Admin}
      - ADMIN_NICKNAME=${ADMIN_NICKNAME:-Admin}
    depends_on:
      gameplan-app:
        condition: service_healthy
    networks:
      - gameplan-network
    command: ["node", "scripts/init-admin.js"]
    restart: "no"
    profiles:
      - init

volumes:
  mongodb_data:
    driver: local

networks:
  gameplan-network:
    driver: bridge
